spring:
  servlet:
    multipart:
      max-file-size: 10MB
  mvc:
    webjars-path-pattern: /wj/**
    static-path-pattern: /**
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      add-mappings: true
      cache:
        cachecontrol:
          max-age: 300

