spring:
  servlet:
    multipart:
      max-file-size: 10MB
  mvc:
    webjars-path-pattern: /wj/**
    static-path-pattern: /**
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      add-mappings: true
      cache:
        cachecontrol:
          max-age: 300
  data:
    redis:
      host: 192.168.0.87
      password: "123456"
      database: 3
  datasource:
    url: jdbc:mysql://192.168.0.121:3306/spring-boot
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

