spring:
  cloud:
    gateway:
      routes:
        - id: order-route
          uri: lb://service-order
          predicates:
            - name: Path
              args:
                patterns: /api/order/**
                matchTrailingSlash: true
          order: 1
        - id: user-route
          uri: lb://service-user
          predicates:
            - name: Path
              args:
                patterns: /api/user/**
                matchTrailingSlash: true
          order: 1
